---
output: 
  html_document:
    code_folding: hide
self_contained: yes
---

```{r, message = F, warning = F}
library(knitr)
library(tidyverse)
library(broom)
library(rgdal)
library(rgeos)
library(sp)
library(raster)
library(gridExtra)
library(ASCI)

opts_chunk$set(message = F, warning = F, fig.path = 'figs/', dev = 'png', dev.args = list(tiff = list(family = 'serif')), dpi = 400, out.width = '50%')

load(file = 'data/sitcat.RData')
data(pkgdat)
data(aldat)

# site categories for h20 combine
sitcat2 <- sitcat %>% 
  mutate(StationCode = gsub('^(.*)_.*_.*$', '\\1', SampleID)) %>% 
  dplyr::select(-SampleID) %>% 
  filter(cls %in% c('rc', 'str'))

# h20 scores
h20 <- aldat %>% 
  dplyr::filter(ind %in% 'H20') %>% 
  mutate(
    StationCode = gsub('^(.*)_.*_.*$', '\\1', SampleID)
    ) %>% 
  left_join(sitcat2, ., by = 'StationCode') %>% 
  mutate(psa = gsub('_', ' ', psa)) %>% 
  filter(!is.na(psa) & !is.na(scr) & !psa %in% 'Central Valley') %>% 
  dplyr::select(-StationCode)

# asci scores, combine with h20
asc <- scores(pkgdat) %>% 
  inner_join(., sitcat, by = 'SampleID') %>% 
  filter(taxa %in% 'hybrid') %>% 
  dplyr::select(SampleID, MMI, cls, psa) %>% 
  filter(cls %in% c('str', 'rc') & !psa %in% 'Central_Valley' & !is.na(psa)) %>% 
  mutate(
    scr = MMI / mean(MMI[cls %in% 'rc'], na.rm = T), 
    ind = 'MMI',
    psa = gsub('_', ' ', psa), 
    StationCode = gsub('^(.*)_.*_.*$', '\\1', SampleID)
    ) %>%
  dplyr::select(cls, psa, SampleID, ind, scr)

# combine
scrs <- rbind(h20, asc)
```

```{r biascmp, fig.height = 5, fig.width = 5}
# get rc only, tenth percentile for thrsh
toplo <- scrs %>% 
  filter(cls %in% 'rc') %>% 
  group_by(ind) %>% 
  mutate(thrsh = quantile(scr, 0.1))
thrsh <- toplo %>% 
  dplyr::select(ind, thrsh)

p1 <- ggplot(toplo, aes(x = psa, y = scr)) + 
  geom_boxplot(outlier.size = 1, alpha = 0.7, fill = 'lightblue') + 
  geom_hline(aes(yintercept = 1)) + 
  geom_hline(aes(yintercept = thrsh), linetype = 'dashed') + 
  scale_y_continuous('Index Score') + 
  facet_wrap(~ind, ncol = 1) +
  theme_minimal(base_family = 'serif', base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    axis.title.x = element_blank(), 
    panel.border = element_rect(colour = 'black', fill = NA, size = 0.5), 
    legend.position = 'none'
  ) 

p1
```

```{r}
##
# testing bias 

# f tests for ref cal of scores by psa, separate for each index
ftst <- toplo %>% 
  nest %>% 
  mutate(ftst = map(data, function(x){
    
    lm(scr ~ psa, x) %>% 
      summary
    
  })) %>%
  dplyr::select(-data) %>% 
  deframe
ftst
```

```{r senscmp, fig.height = 5, fig.width = 5}
toplo <- scrs %>% 
  filter(psa %in% c('North Coast', 'Sierras', 'South Coast')) %>% 
  left_join(thrsh, by = 'ind')

p1 <- ggplot(toplo, aes(x = psa, y = scr, fill = cls)) + 
  geom_boxplot(outlier.size = 1, alpha = 0.7) + 
  geom_hline(aes(yintercept = 1)) + 
  geom_hline(aes(yintercept = thrsh), linetype = 'dashed') + 
  scale_y_continuous('Index Score') + 
  facet_wrap(~ind, ncol = 1) +
  theme_minimal(base_family = 'serif', base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    axis.title.x = element_blank(), 
    panel.border = element_rect(colour = 'black', fill = NA, size = 0.5), 
    legend.position = 'none'
  ) 

p1
```

```{r}
##
# testing sensitivity
ttst <- scrs %>% 
  filter(psa %in% c('North Coast', 'Sierras', 'South Coast')) %>% 
  unite('grp', psa, ind, sep = ', ') %>% 
  group_by(grp) %>% 
  nest %>% 
  mutate(ttst = map(data, function(x){
  
      rc <- filter(x, cls %in% 'rc')$scr
      str <- filter(x, cls %in% 'str')$scr
      t.test(rc, str)
      
    })
  ) %>% 
  dplyr::select(-data) %>% 
  deframe
ttst
```
