---
title: Genus-level ASCI
output: 
  html_document:
    code_folding: hide
self_contained: yes
---

* Summarize traits from selected metrics by genus
* Uses occurrence of species grouped by genus in development (statewide) dataset

```{r, warning = F, message = F}
library(tidyverse)
library(ASCI)

data(taxain)

# add a complete genus column to the traits lookup table
# select only the trait categories used in selected metrics
x <- pmmilkup$traits %>%
  dplyr::select(Phylum, Class, Order, Family, Genus1, FinalIDassigned, everything()) %>% 
  dplyr::select(-orig.FinalID, -AlgaeList) %>% 
  mutate_if(is.factor, as.character) %>% 
  rowwise() %>% 
  mutate(Genus1 = do({
    
    # use genus1 if not empty
    if(Genus1 != '')
      return(Genus1)
    
    chk <- c(Phylum, Class, Order, Family, Genus1)
    
    # get first of FinalIDassigned if all higher taxa cats are empty
    if(all(chk == '')){
      
      out <- strsplit(FinalIDassigned, ' ')[[1]][1]
      
      # get last non-empty cat  
    } else {
      
      out <- chk[chk != ''] %>% rev %>% .[1]
      
    }
    
    return(out)
    
  })
  ) %>% 
  dplyr::select(-Phylum, -Class, -Order, -Family) %>% 
  unique %>% 
  gather('trait', 'est', -Genus1, -FinalIDassigned) %>% 
  rename(FinalID = FinalIDassigned)

# join species level data with genus traits to summarize counts by data dist
to_summ <- taxain %>% 
  left_join(x, by = 'FinalID') %>% 
  mutate(
    Genus1 = ifelse(is.na(Genus1), gsub(' .*$', '', FinalID), Genus1),
    est = ifelse(est %in% '', NA, est)
  )

# summarize trait counts by data dist
traits_gen <- to_summ %>% 
  group_by(Genus1, trait, est) %>% 
  summarise(n = length(est)) %>% 
  group_by(Genus1, trait) %>% 
  mutate(prp = n / sum(n))

print(tbl_df(traits_gen), n = 30)
```

* Traits are assigned to the genus level if more than 75% of species in the genus have a given trait, otherwise NA.  Assignments at higher taxonomic resolution (e.g., family) remain the same.

```{r}
traits_gen <- traits_gen %>% 
  group_by(Genus1, trait) %>% 
  filter(prp > 0.75) %>% 
  ungroup %>% 
  dplyr::select(-prp, -n) %>% 
  spread(trait, est) %>% 
  rename(FinalIDassigned = Genus1)

head(traits_gen)
```

* Indicator species analysis:

```{r, eval = F}
library(tidyverse)
library(indicspecies)
library(ASCI)

data(taxain)
data(sitcat)

indicators <- pmmilkup$indicators %>% 
  rename(FinalID = FinalIDassigned) %>% 
  group_by(designation) %>% 
  nest(.key = 'oldind')

##
# groups for indic
grpin <- sitcat %>% 
  filter(cls %in% c('int', 'rc', 'str')) %>% 
  mutate(
    cls = fct_recode(cls, Intermediate = 'int',  Reference = 'rc', Stressed = 'str'),
    cls = as.character(cls)
  ) %>% 
  dplyr::select(-psa) %>% 
  spread(SampleID, cls) %>% 
  unlist

##
# filter taxonomy data by sites in dev dataset

# format abundance ests
abuin <- taxain %>% 
  dplyr::select(SampleID, FinalID, BAResult, Result) %>% 
  mutate(
    abund = as.numeric(pmax(BAResult, Result, na.rm = T))
    ) %>% # combine abundance 
  dplyr::select(-BAResult, -Result) %>% 
  group_by(SampleID, FinalID) %>% 
  summarise(abund = sum(abund, na.rm = T)) %>%
  ungroup

# remove species that are not ided appropriately
# some species have trailing spaces as duplicates, these are changed
abuin <- abuin %>% 
  filter(!grepl('\\ssp\\s|\\ssp\\.\\s|[0-9]+|\\(|\\)', FinalID)) %>% 
  mutate(nval = sapply(strsplit(FinalID, "\\s+"), length)) %>% 
  filter(nval <= 2) %>% 
  select(-nval) %>% 
  mutate(FinalID = gsub('\\.+$', '', FinalID))

# make wide format, location to rowid
abuin <- abuin %>% 
  spread(FinalID, abund, fill = 0) %>% 
  data.frame(stringsAsFactors = F) %>% 
  remove_rownames %>% 
  column_to_rownames('SampleID')

##
# make sure sites match between grpin and abuin, order is the same
grpin <- grpin[names(grpin) %in% rownames(abuin)]
abuin <- abuin %>% 
  .[rownames(.) %in% names(grpin), ] %>% 
  .[match(rownames(.), names(grpin)), ]

##
# run indicator analysis
res <- multipatt(abuin, grpin, duleg = T, control = how(nperm = 999))

# the A value describes the affinity of a species for each group
# this sums to one for each species across the groups
# it indicates which group a species is most likely to belong
# the B value describes the proportion of sites within a group that have a species, if found in the group
# the final stat value for indic analysis considers A and B
# multipatt returns a pvalue for each species
# the species indicators can be further selected by filtering with an A or B threshold
# the coverage function describes the proportion of sites in each group where one or
# indicators are found for a given threshold, with A = 0 being the default
# using a more conservative, larger A will remove indicator species but this can be done
# up to a threshold until coverage begins to decline

# table of indicator species by pvalue
indic <- res$sign %>%
  rownames_to_column('FinalID') %>% 
  filter(p.value < 0.05) %>% 
  mutate(designation = factor(index, 
                        levels = c('1', '2', '3'), 
                        labels = c('Intermediate', 'Reference', 'Stressed'))
         
         ) %>% 
  select(FinalID, designation, stat, p.value)

# all a values
aval <- res$A %>% 
  data.frame %>% 
  rownames_to_column('FinalID') %>% 
  gather('designation', 'aval', -FinalID)

# find maximum a values without decreasing coverage
chks <- seq(0, 1, by = 0.005)
toplo <- sapply(chks, function(At) coverage(x = abuin, y = res, At = At)) %>% 
  t %>% 
  data.frame %>% 
  mutate(athr = athr) %>% 
  gather('designation', 'cvg', -athr)
athr <- toplo %>% 
  group_by(designation) %>%
  filter(cvg == max(cvg)) %>% 
  filter(athr == max(athr)) %>% 
  select(-cvg) %>% 
  ungroup
# ggplot(toplo, aes(x = aval, y = cvg, group = grp, colour = grp)) + 
#   geom_vline(data = athr, aes(xintercept = aval, colour = grp), linetype = 'dashed') + 
#   geom_line() + 
#   theme_bw()

# join indic with a val, a threshold
indic <- indic %>% 
  left_join(aval, by = c('FinalID', 'designation')) %>% 
  left_join(athr, by = c('designation')) %>% 
  filter(aval >= athr)
  
# check old indicators with new
chk <- indic %>% 
  group_by(designation) %>% 
  nest(.key = 'newind') %>% 
  full_join(indicators, by = 'designation') %>% 
  mutate(
    newind = pmap(list(newind, oldind), function(newind, oldind){
      
      newind <- newind %>% 
        mutate(chk = ifelse(FinalID %in% oldind$FinalID, T, F)) %>% 
        arrange(-stat)
      
      return(newind)
      
    })
  ) %>% 
  select(-oldind) %>% 
  unnest 

```


